### ISSUE TITLE
It doesn't allow <font> tag

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.vdom#2]
According to the standard there should be a font tag:
https://www.w3schools.com/tags/tag_font.asp

**Comment by back2dos** [comment]
Tags are defined in [js-virtual-dom](https://github.com/back2dos/js-virtual-dom/blob/master/src/vdom/VDom.hx#L11) where it could be added in theory.

That said, `font` was deprecated in HTML 4.01 and [MDN explicitly advises *not to use it*](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font).

If you absolutely need this, you can use something like this:

```haxe
class Html3 {
  static public function font(attr:{ ?size:String, ?face:String, ?color:String }):vdom.VNode
    return vdom.VDom.h("font", attr);
}
//and use with
import Html3.*;
```

For better compatibility, you can also try to emulate it with something like this:

```haxe
class Html3 {
  static var sizes = [null, "xx-small", "x-small", "small", "medium", "large", "x-large", "xx-large"];
  static public function font(attr:{ ?size:Int, ?face:String, ?color:String }):vdom.VNode
    return vdom.VDom.span({ style: { fontFace: attr.face, color: attr.color, fontSize: sizes[attr.size] }});
}
```

That said I would still advise against going down that road. You can either use CSS or inline-styles. The latter can be nicely factored out like so:

```haxe
class Styles {
  static public var ERROR(default, never):vdom.Style = { color: 'red' };
  static public var WARNING(default, never):vdom.Style = { color: 'yellow' };
}
//usage:
import Styles.*;
hxx('<span style={WARNING}>You have been warned!</span>');
```

**Comment by grosmar** [comment]
Thanks a lot! :)

Good to know I can easily extend/overwrite existing elements.
