### ISSUE TITLE
Null<tink.domspec.TagInfo> has no field domCt

### ISSUE THREAD

**Issue by dpavicic** [MVCoconut/coconut.vdom#24]
Hi,
I'm trying to build the Mark Knoll's simple example ( https://gist.github.com/markknol/0de2d8d05e8f3d725946eb5515cc771b )
but compilation fails with this errors:

/Users/dinko/haxe/haxelib/coconut,vdom/git/src/coconut/vdom/macros/Setup.hx:18: characters 23-32 : Null<tink.domspec.TagInfo> has no field domCt
/Users/dinko/haxe/haxelib/coconut,vdom/git/src/coconut/vdom/macros/Setup.hx:34: characters 19-28 : Null<tink.domspec.TagInfo> has no field domCt

I have coconut.ui, coconut.data, coconunt.vdom and tink_hxx all 
installed from git so they should be up to date.

I'm not using lix for library management but doing it simple via haxelib and haxelib git install command.

Here's the example project which fails to build.
[coco_test.zip](https://github.com/MVCoconut/coconut.vdom/files/3285145/coco_test.zip)

Cheers,
Dinko

**Comment by back2dos** [comment]
In all likelihood you'll have to use tink_domspec from git as well ;)

**Comment by back2dos** [comment]
Problem will disappear if you update to the latest haxelib versions.
