### ISSUE TITLE
`xdom.html.Dataset` nowhere to be found

### ISSUE THREAD

**Issue by 0b1kn00b** [MVCoconut/coconut.vdom#36]
https://github.com/MVCoconut/coconut.vdom/blob/058fbb7b86580043bea3335ab0a58f863c143b72/src/coconut/vdom/macros/Setup.hx#L48

**Comment by back2dos** [comment]
Meh. Caused by a half-done #25

For the time being you'll have to add https://github.com/back2dos/xDOM as a dependency.

**Comment by 0b1kn00b** [comment]
I also somehow managed to have the wrong `xDOM` version (https://github.com/darmie/xdom.git)
