### ISSUE TITLE
root element is actually not ready in afterInit?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.vdom#4]
I am not very sure about this. But what is happening to me is like this:

```haxe
function render() '<div class="ui dropdown">...</div>';
function afterInit(e) new JQuery(e).dropdown();
```

I am using semantic ui and this code doesn't work. When logging the `e`, it is actually the `div`. But the dropdown initialization doesn't work. However if I wrap the jquery call inside `Callback.defer` it works.

I reckon is problem happens if the view is newly rendered by its parent. So that inside the child view's `afterInit`, `e` is created but not yet mounted to the DOM tree by the parent view, causing this phenomenon.

**Comment by back2dos** [comment]
Works in gen4.
