### ISSUE TITLE
afterInit and beforeInit event called only once in case of rerender

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.vdom#5]
To reproduce:
Create a view component and cause re-renders in any way where the component get destroyed and recreated.

The beforeInit and afterInit lifecycle events doesn't called only the first time. 
For example:
beforeInit 1
render 1
afterInit 1
destroy 1
render 2
destroy 2
render 3
destroy 3
render 4
numbers representing the instance unique id for that is recreate

They should be called properly on every new creation of the object.

**Comment by gene-pavlovsky** [comment]
Maybe this is by design? Can you provide an example?

**Comment by back2dos** [comment]
Should no longer be the case in gen4.
